services:
  yolo:
    command: train
    container_name: yolov8n
    image: yolov8n_image
    env_file:
      - .env
    build:
      context: ./yolov8n
    shm_size: '2gb'
    ports:
      - "8000:8000"
    volumes:
      - ${DATASET_PATH}:/app/dataset
      - ${SCRIPTS_PATH}:/app/scripts
      - ${OUTPUT_PATH}:/app/output
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
              - gpu
              - utility # nvidia-smi
              - compute # CUDA